language: rust

# Test on a recent nightly release.
rust:
  - nightly-2019-09-13

script:
  # Test all feature combinations
  - cargo build --all --no-default-features
  - cargo test --all --no-default-features

  - cargo build --all --no-default-features --features=async-await
  - cargo test --all --no-default-features --features=async-await

  - cargo build --all --no-default-features --features=stream
  - cargo test --all --no-default-features --features=stream

  - cargo test --all --all-features
  - cargo build --all --all-features

# Run this build on the "container-based infrastructure"
# See http://docs.travis-ci.com/user/workers/container-based-infrastructure/.
sudo: false
