[package]

name    = "inotify"
version = "0.5.2-dev"
authors = [
  "Hanno Braun <mail@hannobraun.de>",
  "Félix Saparelli <me@passcod.name>",
  "Cristian Kubis <cristian.kubis@tsunix.de>",
  "Frank Denis <github@pureftpd.org>"
]

description   = "Idiomatic wrapper for inotify"
documentation = "https://docs.rs/inotify"
repository    = "https://github.com/inotify-rs/inotify"
license       = "ISC"
readme        = "README.md"

keywords   = ["inotify", "linux"]
categories = ["api-bindings", "filesystem"]

[badges]
maintenance = { status = "actively-developed" }
travis-ci   = { repository = "inotify-rs/inotify" }

[dependencies]
bitflags    = "1"
futures     = "0.1"
inotify-sys = "0.1.1"
libc        = "0.2"
tokio-core  = "0.1"
tokio-io    = "0.1"
tokio-file-unix = "0.4"

[dev-dependencies]
tempdir = "0.3"

[package.metadata.release]
pre-release-commit-message = "chore: Release version {{version}}"
pro-release-commit-message = "chore: Bump version to {{version}}"
tag-prefix                 = "v"
tag-message                = "Version {{version}}"
dev-version-ext            = "dev"
